source "https://rubygems.org"

gem "jekyll", "~> 3.5"
gem "json", "~> 2.6"
gem "github-pages", group: :jekyll_plugins
gem "tzinfo-data"
gem "webrick", "~> 1.8"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
